okay

diff --git a/.github/workflows/iac-eks.yml b/.github/workflows/iac-eks.yml
--- a/.github/workflows/iac-eks.yml
+++ b/.github/workflows/iac-eks.yml
@@ -1,4 +1,5 @@
 name: "vprofile IAC"
+
 on:
   push:
     branches:
@@ -10,19 +11,20 @@ on:
       - master
     paths:
       - terraform/**
+  workflow_dispatch:
 
 env:
-  # Credentials for deployment to aws
-  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}      
+  # Credentials for deployment to AWS
+  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
   # S3 bucket for terraform state
   BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
   AWS_REGION: us-east-1
-  ESK_CLUSTER: gitops-eks
+  EKS_CLUSTER: gitops-eks
 
 jobs:
-  terraform:
-    name: "Apply terraform code changes"
+  terraform-apply:
+    name: "Apply Terraform Code Changes"
     runs-on: ubuntu-latest
     defaults:
       run:
@@ -35,8 +37,6 @@ jobs:
 
       - name: Setup Terraform with specified version on the runner
         uses: hashicorp/setup-terraform@v2
-        #with:
-        # terraform_version: 1.6.3
 
       - name: Terraform init
         id: init
@@ -57,24 +57,134 @@ jobs:
 
       - name: Terraform plan status
         if: steps.plan.outcome == 'failure'
-        run: exit 1       
+        run: exit 1
 
-      - name: Terraform "Apply
-        id: apple
+      - name: Terraform apply
+        id: apply
         run: terraform apply -auto-approve -input=false -parallelism=1 planfile
 
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v1
         with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
-          aws-region: ${{ env.AWS_REGION }} 
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ${{ env.AWS_REGION }}
 
       - name: Get kube config file
         id: getconfig
-        if: steps.apple.outcome == 'success'
-        run: aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name=gitops-eks
+        if: steps.apply.outcome == 'success'
+        run: aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name=${{ env.EKS_CLUSTER }}
 
       - name: Install Ingress controller
-        if: steps.apple.outcome == 'success' && steps.getconfig.outcome == 'success'
-        run: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.3/deploy/static/provider/aws/deploy.yaml    
+        if: steps.apply.outcome == 'success' && steps.getconfig.outcome == 'success'
+        run: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.3/deploy/static/provider/aws/deploy.yaml
+
+  terraform-destroy:
+    name: "Destroy Terraform Infrastructure"
+    runs-on: ubuntu-latest
+    if: github.event_name == 'workflow_dispatch'
+    defaults:
+      run:
+        shell: bash
+        working-directory: ./terraform
+
+    steps:
+      - name: Checkout source code
+        uses: actions/checkout@v4
+
+      - name: Setup Terraform with specified version on the runner
+        uses: hashicorp/setup-terraform@v2
+
+      - name: Terraform init
+        id: init
+        run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"
+
+      - name: Terraform destroy
+        id: destroy
+        run: terraform destroy -auto-approve -input=false
+
+
+
+
+
+
+#name: "vprofile IAC"
+#on:
+  #push:
+    #branches:
+      #- master
+    #paths:
+      #- terraform/**
+  #pull_request:
+    #branches:
+      #- master
+    #paths:
+      #- terraform/**
+#
+#env:
+  ## Credentials for deployment to aws
+  #AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}      
+  #AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+  ## S3 bucket for terraform state
+  #BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
+  #AWS_REGION: us-east-1
+  #ESK_CLUSTER: gitops-eks
+#
+#jobs:
+  #terraform:
+    #name: "Apply terraform code changes"
+    #runs-on: ubuntu-latest
+    #defaults:
+      #run:
+        #shell: bash
+        #working-directory: ./terraform
+#
+    #steps:
+      #- name: Checkout source code
+        #uses: actions/checkout@v4
+#
+      #- name: Setup Terraform with specified version on the runner
+        #uses: hashicorp/setup-terraform@v2
+        ##with:
+        ## terraform_version: 1.6.3
+#
+      #- name: Terraform init
+        #id: init
+        #run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"
+#
+      #- name: Terraform format
+        #id: fmt
+        #run: terraform fmt -check
+#
+      #- name: Terraform validate
+        #id: validate
+        #run: terraform validate
+#
+      #- name: Terraform plan
+        #id: plan
+        #run: terraform plan -no-color -input=false -out planfile
+        #continue-on-error: true
+#
+      #- name: Terraform plan status
+        #if: steps.plan.outcome == 'failure'
+        #run: exit 1       
+#
+      #- name: Terraform "Apply
+        #id: apple
+        #run: terraform apply -auto-approve -input=false -parallelism=1 planfile
+#
+      #- name: Configure AWS credentials
+        #uses: aws-actions/configure-aws-credentials@v1
+        #with:
+          #aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
+          #aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
+          #aws-region: ${{ env.AWS_REGION }} 
+#
+      #- name: Get kube config file
+        #id: getconfig
+        #if: steps.apple.outcome == 'success'
+        #run: aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name=gitops-eks
+#
+      #- name: Install Ingress controller
+        #if: steps.apple.outcome == 'success' && steps.getconfig.outcome == 'success'
+        #run: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.3/deploy/static/provider/aws/deploy.yaml    
