code apply

diff --git a/.github/workflows/iac-eks.yml b/.github/workflows/iac-eks.yml
--- a/.github/workflows/iac-eks.yml
+++ b/.github/workflows/iac-eks.yml
@@ -4,7 +4,7 @@ on:
     branches:
       - master
     paths:
-      - terraform/*
+      - terraform/**
 
 env:
   # Credentials for deployment to aws
@@ -50,9 +50,9 @@ jobs:
         run: terraform plan -no-color -input=false -out planfile
         continue-on-error: true
 
-      - name: Terraform plan status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1       
+      #- name: Terraform plan status
+        #if: steps.plan.outcome == 'failure'
+        #run: exit 1       
 
       - name: Terraform "Apply
         id: apple
